### ISSUE TITLE
deployment: v0.0.5 release

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#145]
Before tagging

- [x] Review and update examples (#147)
- [x] Review and update dockerfiles (#147)
- [x] Review and update docs (#165)
- [x] Review and update changelog (#166)
- [x] Review and update upgrading guide (#166)
- [x] Anal-retentively check all the examples one last time

After tagging
- [x] Update github release docs
- [x] Publish tagged version of documentation
- [x] Review and update helm-charts (merge after tag) https://github.com/pomerium/pomerium-helm/pull/5

**Comment by desimone** [comment]
tagged @ https://github.com/pomerium/pomerium/releases/tag/v0.0.5
